### ISSUE TITLE
Freestyle Libre 2 Sensor Error

### ISSUE THREAD

**Issue by flackenstein** [bubbledevteam/diabox#30]
Not exactly sure if this is a Diabox issue or Bubble sensor.  Just inserted a new sensor and I get a sensor error.  Sensor works fine with libre app and reader.  On Diabox it shows the correct start time 2021-04-03 13:47, but has the age listed as 19d23h43m with a MaxSensorLife of 14d10h8m.  Sensor serial number is 0M000FHRWN0 with a calibration mode of factory.

Currently using Diabox android version V:2021.04.02.1.  Attached log file for reference.

[2021_04_03_14_18_19.zip](https://github.com/bubbledevteam/diabox/files/6253266/2021_04_03_14_18_19.zip)

**Comment by bubbledevteam** [comment]
Fixed in 2021_04_06 release

**Comment by EdDijk** [comment]
![Screenshot_20210503-170026_DiaBox](https://user-images.githubusercontent.com/81528084/116900548-26437300-ac39-11eb-96a6-2d1332cc654b.jpg)
This is what i get now. 
And i uninstall the app and install again en still the same problem.

**Comment by Eddy69** [comment]
Your problem has nothing to do with DiaBox. The sensor error usually resolves itself by using the standalone reader for your values. Do this a couple of times, until you go to sleep. The next morning the problem is fixed.
For more on this issue, go to the DiaBox Facebook group.

**Comment by EdDijk** [comment]
Hello 
It's working now. 
Only when is the timer working for the readings the 300 seconds. 
--
Ed Dijk maandag, 03 mei 2021, 06:18p.m. +02:00 van Eddy69  ***@***.*** :

**Comment by uschindler** [comment]
Hi @Eddy69 
Can you explain this a bit more. I had the same issue with a sensor around same time (which did not recover). Now I placed a new sensor, activated with reader and scanned with Diabox App. Initially if worked fine for approx 2 hours. Now it can be CamScanner with Reader only and also with official Librelink app on another phone.
But Diabox shows Sensor Error.
